<?php

$orderSimpleProductsCollection = $this->getOrderSimpleProducts();

$baseUrl = Mage::getBaseUrl();
$minQty = Mage::getStoreConfig('customer/customeractivation/min_qty', Mage::app()->getStore());
if($minQty){
?>
<div><h5>Minimum Order Quantity <?php echo $minQty; ?></h5></div>
<?php } ?>
<div class="order_prodct_collection inner-container">
    <form name="" id="" method="post" action="<?php echo Mage::getUrl('*/*/submitorderbySimpleproduct') ?>">
        <div class="third-block grid12-12">
            <?php $i=0; 
            foreach ($orderSimpleProductsCollection as $orderProduct): 
            	?>
                <?php //if ($typeCategory == $orderProduct['category']): ?>
                <div class="order_product grid12-3">
                    <img src="<?php echo $orderProduct['image']; ?>" style="width:200px;" />
                    <div class="order_product_sku">
                        <div class="order_product_name"><a href="<?php echo $baseUrl.$orderProduct['product_url'].'.html'; 
                        ?>"><?php 
                         echo $orderProduct['name']; ?></a></div>
                        <div class="order_product_name"><?php echo $orderProduct['price']; ?></div>
                        <span class="attr-width cart-table">
                            <label>Quantity</label>
                               <?php $skureplace = str_replace(' ', '', $orderProduct['sku']);
                                $skureplace = str_replace("'", "", $skureplace);
                              ?>

                            <?php $sku = $orderProduct['sku']; ?>
                            <input type="text" class="input-text qty" onchange="qtyCalculate('<?php echo $skureplace . '_' . $i; ?>', '<?php echo count($orderProduct['sku']); ?>')" name="<?php echo $orderProduct['product_id'] ?>_<?php echo $sku; ?>" id="<?php echo $skureplace . '_' . $i; ?>" value=""/>
                        </span>

                        <b><span class="totalcount" name="total" id="<?php //echo $skureplace; ?>"></span></b>

                    </div>

                </div>
                 <?php $i++;
                if($i%4==0){?>
                    <div class="clear"></div>
                <?php }
                    ?>
            <?php endforeach; ?></div> 
<div><input type="submit"  class="add_to_basket button float-right" name="Add to Basket" value="Add to Basket"></div>
</form>
 </div>

<script type="text/javascript">
    function qtyCalculate(sku, count) {
        var totalsku = sku.split('_');
        var totQty = 0;
        for (var i = 1; i <= count; i++) {
            var qty = parseInt(document.getElementById(totalsku[0] + '_' + i).value);
            if (isNaN(qty))
            {
                qty = 0;
            }
            totQty = totQty + qty;
        }
        document.getElementById(totalsku[0]).innerHTML = totQty;
    }

</script> 
<style type="text/css">
    .attr-width{display:inline-block;}
    .attr-width label{padding: 0 5px;}
    .order_prodct_collection{border:1px solid #ccc;}
    .order_product{ float: left; margin: 5px 0; padding: 10px;}
    .order_product:first-child{border-top:0 !important;}
    .order_product_qty .attr-width{color:red;}
    .order_product_attr .attr-width, .order_product_qty .attr-width,
    .order_product_sku .attr-width{margin-top:9px;}
    .order_product_name {font-weight:bold;font-size:14px;}
    .clear{clear:both;}
    .add_to_basket.float-right {margin: 10px;}
    .customeractivation-productorder-quickorderproduct .my-account h2 {display: inline-block; padding: 0 9px;}
    .grid12-3 {width: 21%;}
    .grid12-1, .grid12-2, .grid12-3, .grid12-4, .grid12-5, .grid12-6, .grid12-7, .grid12-8, .grid12-9, .grid12-10, .grid12-11, .grid12-12, .grid-full, .grid-col2-sidebar, .grid-col2-main { display: inline; float: left; margin-left: 1%; margin-right: 1%;  }
    .grid12-1 {width: 6.33%;}
    .grid12-8 {width: 64.67%;}
    .inner-container:before, .inner-container:after {content: "";display: table; line-height: 0;}
    .inner-container:after { clear: both;}
    .inner-container { clear: both; padding-left: 15px; padding-right: 15px;}
    .clearer:after { clear: both; content: "."; display: block; font-size: 0; height: 0; line-height: 0; overflow: hidden; }
</style>
