<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login <?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?> ">

    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo Mage::getBaseUrl() . 'customerActivation/account/loginPost'; ?>" method="post" id="login-form" class="scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <div class="col-1 new-users">
                    <div class="content">
                        <h2><?php echo $this->__('New Here?') ?></h2>
                        <p class="form-instructions"><?php echo $this->__('Registration is free and easy!') ?></p>
                        <ul class="benefits">
                            <li><?php echo $this->__('Faster checkout') ?></li>
                            <li><?php echo $this->__('Save multiple shipping addresses') ?></li>
                            <li><?php echo $this->__('View and track orders and more') ?></li>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <a  title="<?php echo $this->__('Wholesale Registration') ?>" class="button" href = "<?php echo Mage::getBaseUrl() . 'customerActivation/index/wholesale'; ?> "><span><span><?php echo $this->__('Wholesale Registration') ?></span></span></a>
                    </div>
                </div>
            <?php endif; ?>
            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>col-2<?php else: ?>col-1<?php endif; ?> registered-users">
                <div class="content fieldset">
                    <h2><?php echo $this->__('Already registered?') ?></h2>
                    <p class="form-instructions"><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email"><em>*</em><?php echo $this->__('Account Id') ?></label>
                            <div class="input-box">
                                <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <li>
                            <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                        </li>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        <input type="hidden" name="groupname" value="2" />
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    <br/><br/>

                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>

    <style type="text/css">
        .col3-layout .col-wrapper .col-main {
            float: none;
            width: auto;
            padding: 0;
        }
        .buttons-set{margin-right:219px;border-top:0;}
        .col2-set .col-2 {border-left: 1px solid #ededed;}
    </style>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
