<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php if ($this->isAmazonPayButtonEnabled()): ?>

  <div id="<?php echo $this->getAmazonPayButtonId(); ?>" style="clear:both;"></div>

  <script type="text/javascript">
    var authRequest;

    var AmazonButtonOptions = {
        type: "<?php echo $this->getButtonType(); ?>",
        color: "<?php echo $this->getButtonColor(); ?>",
        size: "<?php echo $this->getButtonSize(); ?>",
        authorization: function() {
            loginOptions = {
                scope: "profile payments:widget payments:shipping_address<?php print $this->getAdditionalScope(); ?>",
                response_type: 'token',
                popup: <?php print $this->isPopup(); ?>
            };

            authRequest = amazon.Login.authorize (loginOptions, "<?php echo !$this->isPopup() ? $this->getLoginAuthUrl() : $this->getCheckoutUrl(); ?>");
        },
        onError: function(error) {
            console.log(error);
        }
    };

    OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);

  </script>


<script type="text/javascript">

    // OffAmazonPayments.jQuery loaded by Amazon API

    var productAddToCartFormAmazon =  new VarienForm('product_addtocart_form');

    productAddToCartFormAmazon.submit = function(button) {
        if (this.validator.validate()) {
            var form = this.form;
            var url = form.action;

            var e = null;

            var data = OffAmazonPayments.jQuery(form).serialize();
            data += '&isAjax=1';
            OffAmazonPayments.jQuery('#ajax_loader').show();

            if (document.location.protocol == 'https:') {
                url = url.replace('http:', document.location.protocol);
            }
            else {
                url = url.replace('https:', document.location.protocol);
            }

            // Add via Ajax and redirect to login/payment page
            OffAmazonPayments.jQuery.post(url, data,
                function(){
                    OffAmazonPayments.jQuery('#ajax_loader').hide();
                    OffAmazonPayments.jQuery("#<?php echo $this->getAmazonPayButtonId(); ?> img[id!='amazon-button-clone']").click();
                }
            )
            ;

        }
    }.bind(productAddToCartFormAmazon);


    // Duplicate Amazon button
    OffAmazonPayments.jQuery("#<?php echo $this->getAmazonPayButtonId(); ?> img")
        .hide()
        .clone()
        .attr("id", "amazon-button-clone")
        .show()
        .appendTo("#<?php echo $this->getAmazonPayButtonId(); ?>")
        .click(productAddToCartFormAmazon.submit);


</script>

<?php endif; ?>