<?php /*<h2><?php echo $this->__(Mage::getStoreConfig('clnews/news/title')) ?>
<?php if (Mage::getStoreConfig('clnews/rss/enable')): ?>
    <?php if ($this->getCurrentCategory()): ?>
    <?php $categoryId = $this->getCurrentCategory()->getId() ?>
    <?php endif ?>
    <a href="<?php echo Mage::Helper('clnews')->getRssLink(isset($categoryId)?$categoryId:null) ?>">
        <img src="<?php echo $this->getSkinUrl('css/clnews/images/rss.gif') ?>">
    </a>
<?php endif ?>
</h2> */
 ?>





<div class="vce-sid-right">



<div class="blogimages"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-blog-image')->toHtml(); ?>
</div>
	
		
		<div id="content" class="container site-content">
			<div class="vce-main-content">
			<?php $categories = $this->getCategories();
             			
			?>
			<?php //$items = $this->getNewsItems(); ?>
			
			<?php foreach ($categories as $category): ?>
			<?php //sort($category); ?>
			<div id="primary" >
					<div class="vce-module-columns">

						<div id="main-box-4" class="main-box vce-border-top main-box-half" >
							
							
							<?php //$items = $this->getNewsItems(); 
								  //$items->addFieldToFilter('category_id','3');
								$collection = Mage::getModel('clnews/news')->getCollection();
								//$collection ->addFieldToFilter('update_time',Varien_Data_Collection::SORT_ORDER_ASC);
								
								$collection ->addFieldToFilter('categories',$category->getId());
								
								$collection->addEnableFilter(1);
								$collection->setPageSize(10);
								$collection->addFieldToFilter('publicate_from_time', array('or' => array(
                                  0 => array('date' => true, 'to' => date('Y-m-d H:i:s')),
                                  1 => array('is' => new Zend_Db_Expr('null'))),
                                   ), 'left');
                              $collection->addFieldToFilter('publicate_to_time', array('or' => array(
                                       0 => array('date' => true, 'from' => date('Y-m-d H:i:s')),
                                        1 => array('is' => new Zend_Db_Expr('null'))),
                                        ), 'left');
										$collection->setOrder('update_time', 'DESC');
								//->addAttributeToSort('name', Varien_Data_Collection::SORT_ORDER_ASC);
						 		$a=$collection->count();
       					?>
							<?php //$date = Mage::getModel('CommerceLab_News/clnews_news'); 
							// 	  $item = $date->getCollection();
							?>
							<?php //echo $sort_order=$category->getSort_order(); ?>
							
					<?php if($a>0): ?>
					
                    
					<h3 class="main-box-title cat-448"><?php echo $category->getTitle() ?></h3>
					
						
						<?php foreach ($collection as $item): ?>

							<div class="main-box-inside ">
								<div class="vce-loop-wrap" >
									<article class="vce-post vce-lay-d post-4163 post type-post status-publish format-standard has-post-thumbnail hentry category-grooming category-hair-care-grooming tag-skincare-encyclopedia tag-thinning-hair" >
									<div class="meta-image">
										<?php if ($item->getImageShortContentShow() && $item->getImageShortContent()): ?>
		       							 <?php $imageSize = $this->getShortImageSize($item) ?>
										<a href="<?php echo $item->getUrl($this->getCategory()) ?>" title="">
										<img width="145" height="89" src="<?php echo Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageShortContent()), $imageSize['width'], $imageSize['height'], 'clnews'); ?>" class="attachment-vce-lay-d size-vce-lay-d wp-post-image" >
										</a>
		 								<?php endif; ?>
		        					</div>
									<header class="entry-header">
									<h2 class="entry-title"><a href="<?php echo $item->getUrl($this->getCategory()) ?>" title="What to Do About Thinning Hair"><?php echo $item->getTitle();?></a></h2></br>
									<?php $d = $item->getShortContent();
												//strlen($d);
									?>
									<p class="entry-title">
										<?php if($d):?>	
											<?php echo substr($d,0,150).'....!!';?>
										<?php endif;?>
									</p>
									
									<time class="rpwe-time published"><?php echo 'Published on: '.$item->getUpdateTime();?>
									<?php if($item->getAuthor()): ?>
		                               <p style="float:right;"><span style="font-weight: bold; margin-right: 5px;">
                                       Author: </span><?php echo $item->getAuthor(); ?></p>
                                    <?php endif; ?>
									</time>
									</header>
									</article>
								</div>
							</div>
						<?php endforeach; ?>
						<?php endif;?>	
						</div>
						

					</div>
			</div>
			<?php endforeach; ?>
			
			</div>
			
			<?php $categories = $this->getCategories() ?>
			<?php //foreach ($categories as $category): ?>
			
			<?php //$items = $this->getNewsItems(); 
								  //$items->addFieldToFilter('category_id','3');
								$collection = Mage::getModel('clnews/news')->getCollection();
								//$collection ->addFieldToFilter('update_time',Varien_Data_Collection::SORT_ORDER_ASC);
								
								//$collection ->addFieldToFilter('tag',$category->getId());
								//$collection->setOrder('tag', 'DESC');
								//->addAttributeToSort('name', Varien_Data_Collection::SORT_ORDER_ASC);
						 		//$a=$collection->count();
       					?>
						<?php /* ?>
							<aside id="sidebar" class="sidebar right">
<div id="rpwe_widget-3" class="widget rpwe_widget recent-posts-extended">
				<h4 class="widget-title">Tags</h4>
				<div class="rpwe-block ">
					<ul class="rpwe-ul">
						
						<?php foreach ($collection as $item): ?>
						
					
						<li class="rpwe-li rpwe-clearfix">
						<h3 class="rpwe-title"><a href="<?php echo $item->getUrl() ?>" title="Permalink to 5 Ways to Boost Your Confidence" rel="bookmark"><?php echo $item->getTags(); ?></a></h3>
						<?php //echo $item->getCreated_time() ?>
						</li>
						
						
						
					
						
			           <?php endforeach; ?>
					   
				</ul>
				</div>
			</div>
		</aside>
		
		<?php */ ?>
<?php $collection1 = Mage::getModel('clnews/news')->getCollection(); 
$collection1->setOrder('created_time', 'DESC');
//$fromDate = date('Y-m-d H:i:s', strtotime('-1 hour'));

//$toDate = date('Y-m-d H:i:s', strtotime(now()));
//$collection1->addFieldToFilter('created_time', array(
  //  'from' => $fromDate,
   // 'to' => $toDate,
   // 'date' => true,
    //));

?>
<!--<div class="drop_section">
						
                         <p class="acc_trigger active">Tags1</p>
                        <div class="acc_container ">iy dfsf dfg gd</div>	
                         <p class="acc_trigger">Tags2</p>
                        <div class="acc_container ">iy getCreated_time</div>
                        <p class="acc_trigger">Tags3</p>
                        <div class="acc_container ">iy getCreated_time</div>
                        <p class="acc_trigger">Tags4</p>
                        <div class="acc_container ">iy getCreated_time</div>						
                        </div>-->

<aside id="sidebar" class="sidebar right">




             <div id="rpwe_widget-3" class="widget rpwe_widget recent-posts-extended">
			 
 
				<h4 class="widget-title">Blog Archive</h4>
				    <div class="rpwe-block ">
					   
						
						<?php 
							$_track_post_year = '';
						foreach ($collection1 as $key=>$item1): ?>
						
					
						
						<?php   $timedate=$item1->getCreated_time(); 
						
							$post_year = date('Y', strtotime($item1->getCreated_time()));
							if($post_year != $_track_post_year) {
								?>
								
								
							<?php
           						//echo $timedate=$item1->getCreated_time();	
								
								
								$fromDate = date('Y-m-d H:i:s', strtotime($post_year.'-01-31'));
								$toDate = date('Y-m-d H:i:s', strtotime($post_year.'-12-31'));
								
								
							?>
							  <?php $collection2 = Mage::getModel('clnews/news')->getCollection(); 
							  //$collection2->addFieldToFilter('created_time', $post_year)
							  $collection2->addFieldToFilter('created_time', array(
									'from' => $fromDate,
									'to' => $toDate,
									'date' => true,
									));
							  
							  ?>
							 
							  
						<div class="drop_section">
							 <p   class="acc_trigger" style="padding-top: 18px;" ><b><?php echo $post_year; ?></b></p>
							<ul class="acc_container">
							<?php foreach ($collection2 as $item2): ?>
							<li>
							
							<a href="<?php echo $item2->getUrl(); ?>">
							<?php echo $item2->getTitle(); ?>
							
							</a>
							</li>
							<?php endforeach; ?>
							</ul>
						</div>
                           <?php }	?>						
						
			           <?php 
						$_track_post_year = $post_year; ?>
						
						
					  <?php  endforeach; ?>
					   
				
				
			</div>
		</aside>			
					   
					   
		    <?php //endforeach; ?>			   
			
			

       <?php $categories = $this->getCategories() ?>
	   <?php  ?>
			<?php foreach ($categories as $category): ?>
			
            

			<aside id="sidebar" class="sidebar right">
			
			
			
			

			<div id="rpwe_widget-5" class="widget rpwe_widget recent-posts-extended">
			<?php //$items = $this->getNewsItems(); 
								  //$items->addFieldToFilter('category_id','3');
								$collection = Mage::getModel('clnews/news')->getCollection();
								
								$collection ->addFieldToFilter('categories',$category->getId());
								//$collection ->addFieldToFilter('categories','DESC');
						 		$a=$collection->count();
       					?>
							<?php //$date = Mage::getModel('CommerceLab_News/clnews_news'); 
							// 	  $item = $date->getCollection();
							?>
					<?php if($a>0): ?>
				<h4 class="widget-title"><?php echo $category->getTitle() ?></h4>
				
			
			
				<div class="rpwe-block ">
					<ul class="rpwe-ul">
					
					
					
					<?php foreach ($collection as $item): ?>
					<?php $con=1;?>
					<?php if($con<=3): ?> 
						<li class="rpwe-li rpwe-clearfix">
						<?php if ($item->getImageShortContentShow() && $item->getImageShortContent()): ?>
		       							 <?php $imageSize = $this->getShortImageSize($item) ?>
										<a class="rpwe-img" href="<?php echo $item->getUrl($this->getCategory()); ?>" title="">
										<img width="45" height="45" class="rpwe-alignleft rpwe-thumb" src="<?php echo Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageShortContent()), $imageSize['width'], $imageSize['height'], 'clnews'); ?>" class="attachment-vce-lay-d size-vce-lay-d wp-post-image" >
										</a>
		 								<?php endif; ?>
						
						
						<h3 class="rpwe-title"><a href="<?php echo $item->getUrl($this->getCategory()); ?>" title="Permalink to Get the Closest Shave Ever" rel="bookmark"><?php echo $item->getTitle(); ?></a></h3>
						<time class="rpwe-time published" datetime="2013-08-22T15:51:25+00:00"><?php echo 'Published on: '.$item->getUpdateTime();?></time></li>
						<?php endif;
						$con++; ?>
					<?php endforeach; ?>
						
					</ul>
				</div>
				<?php endif; ?>
			</div>

			<!--<div id="rpwe_widget-3" class="widget rpwe_widget recent-posts-extended">
				<h4 class="widget-title">Grooming</h4>
				<div class="rpwe-block ">
					<ul class="rpwe-ul">
						<li class="rpwe-li rpwe-clearfix"><a class="rpwe-img" href="http://blog.menscience.com/how-to-boost-your-confidence/" rel="bookmark"><img class="rpwe-alignleft rpwe-thumb" src="http://blog.menscience.com/wp-content/uploads/2014/01/5-Ways-to-Boost-Your-Confidence-45x45.jpg" alt="5 Ways to Boost Your Confidence"></a>
						<h3 class="rpwe-title"><a href="http://blog.menscience.com/how-to-boost-your-confidence/" title="Permalink to 5 Ways to Boost Your Confidence" rel="bookmark">5 Ways to Boost Your Confidence</a></h3>
						</li>
						<li class="rpwe-li rpwe-clearfix"><a class="rpwe-img" href="http://blog.menscience.com/how-to-get-a-close-shave/" rel="bookmark"><img class="rpwe-alignleft rpwe-thumb" src="http://blog.menscience.com/wp-content/uploads/2013/08/theperfectshaveformen-45x45.jpg" alt="Get the Closest Shave Ever"></a>
						<h3 class="rpwe-title"><a href="http://blog.menscience.com/how-to-get-a-close-shave/" title="Permalink to Get the Closest Shave Ever" rel="bookmark">Get the Closest Shave Ever</a></h3>
						</li>
						
						
					</ul>
				</div>
			</div>-->
			
			

	</aside>

   <?php endforeach; ?>
	</div>













<STYLE TYPE="text/css">
.rpwe-block ul{list-style:none!important;margin-left:0!important;padding-left:0!important;}.rpwe-block li{border-bottom:1px solid #eee;margin-bottom:0px;padding-bottom:0px;list-style-type: none;}.rpwe-block a{display:inline!important;text-decoration:none;}.rpwe-block h3{background:none!important;clear:none;margin-bottom:0!important;margin-top:0!important;font-weight:400;font-size:14px!important;line-height:1.5em;}.rpwe-thumb{border:1px solid #EEE!important;box-shadow:none!important;margin:2px 10px 2px 0;padding:3px!important;}.rpwe-summary{font-size:12px;}.rpwe-time{color:#bbb;font-size:11px;}.rpwe-comment{color:#bbb;font-size:11px;padding-left:5px;}.rpwe-alignleft{display:inline;float:left;}.rpwe-alignright{display:inline;float:right;}.rpwe-aligncenter{display:block;margin-left: auto;margin-right: auto;}.rpwe-clearfix:before,.rpwe-clearfix:after{content:"";display:table !important;}.rpwe-clearfix:after{clear:both;}.rpwe-clearfix{zoom:1;}


.BlogArchive #ArchiveList ul {
    margin: 0;
    padding: 0;
    list-style: none;
    list-style-image: none;
    border-width: 0;
}

.BlogArchive #ArchiveList ul li {
    background: none;
    list-style: none;
    list-style-image: none;
    list-style-position: outside;
    border-width: 0;
    padding-left: 15px;
    text-indent: -15px;
    margin: .25em 0;
    background-image: none;
}
#ArchiveList a.toggle, #ArchiveList a.toggle:link, #ArchiveList a.toggle:visited, #ArchiveList a.toggle:hover {
    color: inherit;
    text-decoration: none;
}

58827200-widget…s_bundle.css:1
#ArchiveList .toggle {
    cursor: pointer;
    font-family: Arial,sans-serif;
}

.acc_trigger {position:relative; padding:5px 18px !important; font-size:18px;}

.acc_trigger:after{position:absolute;left:0px; top:5px;content:"";

  width: 0; 
  height: 0; 
  border-top: 8px solid transparent;
  border-bottom: 8px solid transparent; 

  border-left:8px solid #000; 

 }
p.active {
    background: rgba(0, 0, 0, 0.81);
    color: #fff ;
}
p.active:after{
  border-left:8px solid #fff !important; 

 }
 ul.acc_container {
    padding-bottom: 20px;
	height:160px;
	overflow:auto;
	
}
.drop_section{
	background:#f1f1f1;
}
.acc_trigger{
background:#fff;
margin:10px 0px;
}

</STYLE>

<script>
    jQuery("document").ready( function () {
		
         jQuery('.acc_container').hide(); //Hide/close all containers
        //jQuery('.acc_trigger:first').addClass('active').next().show();
		
		  jQuery('.acc_trigger').click(function(){
            if( jQuery(this).next().is(':hidden') ) { //If immediate next container is closed...
                jQuery('.acc_trigger').removeClass('active').next().slideUp(); //Remove all "active" state and slide up the immediate next container
                jQuery(this).toggleClass('active').next().slideDown(); //Add "active" state to clicked trigger and slide down the immediate next container
            }
            return false; //Prevent the browser jump to the link anchor
        });
		
    }); 
</script>


</div>

