<?php
$customerId = $this->getRequest()->getParam('id');
$customerData = Mage::getSingleton('customer/customer')->load($customerId);
?>
<?php $_element = $this->getElement() ?>
<?php echo $_element->getFieldsetContainerId(); ?>
<?php if ($_element->getFieldsetContainerId()): ?>

    <div id="<?php echo $_element->getFieldsetContainerId(); ?>">
    <?php endif; ?>
    <?php if ($_element->getLegend()): ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
            <div class="form-buttons"><?php echo $_element->getHeaderBar() ?></div>
        </div>
    <?php endif; ?>
    <?php if (!$_element->getNoContainer()): ?>

        <div class="fieldset <?php echo $_element->getClass() ?>" id="<?php echo $_element->getHtmlId() ?>">
        <?php endif; ?>
        <div class="hor-scroll">
            <?php if ($_element->getComment()): ?>
                <p class="comment"><?php echo $this->escapeHtml($_element->getComment()) ?></p>
            <?php endif; ?>
            <?php if ($_element->hasHtmlContent()): ?>
                <?php echo $_element->getHtmlContent(); ?>
            <?php else: ?>
                <table cellspacing="0" class="<?php echo $_element->hasTableClass() ? $_element->getTableClass() : 'form-list' ?>">
                    <?php $img = $_element->getFieldsetContainerId(); ?>
                    <tbody>
                        <?php echo $_element->getChildrenHtml(); ?>

                        <?php if ($_element->getHtmlId() == '_accountbase_fieldset'): ?>

                            <tr>
                                <td></td>
                                <td>
                                    <?php if ($customerData->getLogoImage() != ''): ?>
                                        <a target="_blank" href ="<?php echo Mage::getBaseUrl('media') . $customerData->getLogoImage() ?>"><img src  = "<?php echo Mage::getBaseUrl('media') . $customerData->getLogoImage() ?>" width="20%" height="20%"/></a>
                                    <?php endif; ?>
                                </td>
                            </tr> 
                        <?php endif; ?>


                    </tbody>
                </table>
            <?php endif; ?>
        </div>

        <?php echo $_element->getSubFieldsetHtml() ?>
        <?php if (!$_element->getNoContainer()): ?>

        </div>
    <?php endif; ?>
    <?php if ($_element->getFieldsetContainerId()): ?>
    </div>
<?php endif; ?>
