<form action="<?php echo Mage::getUrl('photo/index/save') ?>" method="post">
  <fieldset>
    <ul>
     <li>
       <label for="title">Title</label>
       <input type="text" id="nom" name="title" />
     </li>
     <li>
         <label for="image">Image</label>
         <input type="text" id="prenom" name="image" />
     </li>
<!--     <li>
        <label for="nom">Telephone</label>
        <input type="text" id="telephone" name="telephone" />
    </li>-->
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>