<div class="std testimonials_container">
    <h1 class="testimonials_title"><?php echo Mage::helper('testimonialmanager')->__('Write Testimonials'); ?></h1>
    <div class="testimonials-form">
		<form id="testimonialForm" name="testimonialForm" action="<?php echo $this->_getSubmitUrl() ?>" method="post" enctype="multipart/form-data">
            <table cellspacing="0" class="form-list" width="500">
                <tbody>
                    <tr>
                        <td class="label"><label for="testimonial_name"><?php echo Mage::helper('testimonialmanager')->__('Contact Name') ?> <span class="required">*</span></label></td>
                        <td class="value"><input type="text" class=" input-text required-entry" value="" name="testimonial_name" id="testimonial_name"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_company"><?php echo Mage::helper('testimonialmanager')->__('Company') ?></label></td>
                        <td class="value"><input type="text" class=" input-text" value="" name="testimonial_company" id="testimonial_company"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_email"><?php echo Mage::helper('testimonialmanager')->__('Email') ?> <span class="required">*</span></label></td>
                        <td class="value"><input type="text" class=" validate-email input-text required-entry" value="" name="testimonial_email" id="testimonial_email"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_website"><?php echo Mage::helper('testimonialmanager')->__('Website URL') ?></label></td>
                        <td class="value"><input type="text" class="validate-clean-url input-text" value="" name="testimonial_website" id="testimonial_website"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_img"><?php echo Mage::helper('testimonialmanager')->__('Image') ?></label></td>
                        <td class="value"><input type="file" class="input-file" name="testimonial_img" id="testimonial_img"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="detailed_rating" class="rating"><?php echo Mage::helper('testimonialmanager')->__('Rating') ?> <span class="required">*</span></label></td>
                        <td class="value">
                            <span id="detailed_rating"><div id="rating_detail"><div class="product-review-box">
                            <table cellspacing="0" id="product-review-table" width="250">
                                <thead>
                                <tr>
                                        <th><span class="nobr"><b><?php echo '1 star'; ?></b> </span></th>
									<?php for ($i=2; $i<=5; $i++) { ?>
                                        <th><span class="nobr"><b><?php echo $i . ' stars'; ?></b> </span></th>
                                    <?php } ?>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr class="odd last">
										<?php for ($i=1; $i<=5; $i++) { ?>
                                            <td<?php if($i == 5): ?> class="last"<?php endif; ?>><input type="radio" name="rating_summary" id="rating_<?php echo $i;?>" value="<?php echo $i ?>" checked="checked" /></td>
                                        <?php } ?>
                                    </tr>
                                </tbody>
                            </table>
                            </div></div></span>
                        </td>
                    </tr>
                    
                    <tr>
                        <td class="label"><label for="testimonial_text"><?php echo Mage::helper('testimonialmanager')->__('Text') ?> <span class="required">*</span></label></td>
                        <td class="value">
                            <textarea class=" required-entry textarea" cols="15" rows="2" style="width:100%;height:200px;" title="Text" name="testimonial_text" id="testimonial_text"></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
            
            <div class="buttons-set">
                <button class="button" title="Submit Review" type="submit"><span><span><?php echo Mage::helper('testimonialmanager')->__('Submit Testimonial') ?></span></span></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonialForm', true);
//]]>
</script>