<div id="main-wrapper">


<div id="content" class="container site-content">

				
	<div id="primary" class="vce-main-content">

		<main id="main" class="main-box main-box-single">

		
			<article id="post-4752" class="vce-single post-4752 post type-post status-publish format-standard has-post-thumbnail hentry category-exercise tag-workout-results">

			<header class="entry-header">
							<!--<span class="meta-category"><a href="http://blog.menscience.com/category/fitness/exercise/" class="category-3">Exercise</a></span>-->
							<?php $item = $this->getNewsitem(); ?>
    						<!--<h4><?php //echo $item->getTitle() ?></h4>-->
			
			<h1 class="entry-title"><?php echo $item->getTitle() ?></h1>
			<div class="entry-meta"></div>
		</header>
		
		
	
	<?php if ($item->getImageFullContentShow() && $item->getImageFullContent()): ?>
        <div class="meta-image">
            <?php $imageSize = $this->getFullImageSize($item) ?>
            <img width="568" height="350" src="<?php echo Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageFullContent()), $imageSize['width'], $imageSize['height'], 'clnews'); ?>" />
        </div>
    <?php endif; ?>
	
	
	
   
	<div class="entry-content">

	
	<div class="ftg" >

        
        <?php if (Mage::helper('clnews')->getFaceBookAccess()): ?>
		
            <div id="fb-root"></div>
            <script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getDefaultLocale() ?>/all.js#xfbml=1";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
            <div class="fb-like" data-send="false" data-layout="button_count" data-width="110" data-show-faces="false"></div>
			
        <?php endif; ?>
		<?php if (Mage::helper('clnews')->getGoogleAccess()): ?>
            <script type="text/javascript">
                (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/plusone.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                    <?php if (isset($comments) && count($comments)): ?>
                        AjaxSend(1, <?php echo $item->getID() ?>, false);
                    <?php endif ?>
                })();
            </script>
            <div class="google_button"><g:plusone></g:plusone></div>
        <?php endif; ?>
		
        <?php if (Mage::helper('clnews')->getLinkedInAccess()): ?>
            <script src="http://platform.linkedin.com/in.js" type="text/javascript"></script>
            <script type="IN/Share" data-counter="right"></script>
        <?php endif; ?>
        <?php if (Mage::helper('clnews')->getTwitterAccess()): ?>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            <a href="https://twitter.com/share" class="twitter-share-button" style="float:right;">Tweet</a>
        <?php endif; ?>
        <!--<a href="<?php //echo $item->getUrl() ?>?mode=print" class="print-btn"><?php //echo $this->__('Print Version'); ?></a>-->
       
	</div>	
	
		<p><?php echo Mage::helper('clnews')->contentFilter($item->getFullContent()) ?></p>
		<?php if($item->getAuthor()): ?>
		<p><span style="font-weight: bold; margin-right: 5px;">
    Author: </span><?php echo $item->getAuthor(); ?></p>
     <?php endif; ?>
	<span id="pty_trigger"></span>
	</div>
</article>
	</main>


	

		
		
		

		<?php
		 $cat=$item->getCategories();
		$collection = Mage::getModel('clnews/news')->getCollection();
		$collection ->addFieldToFilter('categories',$cat);
		$collection ->setPageSize(6);
		//foreach($collection as $item):
		//echo $item1->getId();
		//echo "hii".$item->getTitle();
		//endforeach;
		
		?>
					
	
	<div class="main-box vce-related-box">

	<h3 class="main-box-title">You may also like</h3>
	
	<?php
	//$collection = Mage::getModel('clnews/news')->getCollection()
         // ->addStoreFilter(Mage::app()->getStore()->getId());
			//$collection->addFieldToFilter( 'url_key', );
			//$collection1 = Mage::getModel('clnews/category')->getCollection()
			//->addStoreFilter(Mage::app()->getStore()->getId());
		//$collection1->addFieldToFilter( 'url_key',$item->getUrl());
		//foreach($collection1 as $cat):
		
		//$collection2 = Mage::getModel('clnews/news')->getCollection();
		//$collection2 ->addFieldToFilter('categories',$cat->getId());
		 //echo $cat->getId();
		 //foreach($collection2 as $item1):
		  //echo $item1->getTitle();
		 //echo $item1->getId();
		 
		//endforeach;
        //endforeach; 
		//$collection = Mage::getModel('clnews/category')->getCollection()
        //->addStoreFilter(Mage::app()->getStore()->getId());
        
		////foreach($collection as $item1):
		//echo $item1->getId();
		//echo $item1->getTitle()
		//endforeach;
		//$collection = Mage::getModel('clnews/news')->getCollection()
          //->addFieldToFilter('title',$item->getCategories());
			
			//foreach($collection as $item1):
		//echo $item1->getId();
		//echo $item1->getTitle()
		//endforeach;
		//$collection = Mage::getModel('clnews/news')->getCollection();
		//$collection ->addFieldToFilter('categories',$cat);
		
		//echo $item1->getId();
		//echo "hii".$item->getTitle();
		//endforeach;
		
	?>		
	
	<div class="main-box-inside1">
 <?php foreach($collection as $item): ?>
	<article class="vce-post vce-lay-d post-4680 post type-post status-publish format-standard has-post-thumbnail hentry category-exercise tag-bigger-arms tag-muscle-growth" style="height: 100px;">
	 <div class="meta-image">
	<?php if ($item->getImageFullContentShow() && $item->getImageFullContent()): ?>
	<?php $imageSize = $this->getShortImageSize($item) ?>
	<a href="<?php echo str_replace('clnews', $item->getAlias(), $item->getUrl()); ?>" title="How to Get Bigger Arms">
	<img width="145" height="89"  src="<?php echo Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageFullContent()), $imageSize['width'], $imageSize['height'], 'clnews'); ?>" alt="Win the Battle Against Men’s Body Acne" width="45" height="45"></a>
	</a>
	<?php endif; ?>
	</div>
	
	
 		<!-- <div class="meta-image">			
			<a href="http://blog.menscience.com/how-to-get-bigger-arms/" title="How to Get Bigger Arms">
				<img width="145" height="89" src="http://blog.menscience.com/wp-content/uploads/2013/09/howtogetbiggerarms-145x89.jpg" class="attachment-vce-lay-d size-vce-lay-d wp-post-image" alt="how to get bigger arms" srcset="http://blog.menscience.com/wp-content/uploads/2013/09/howtogetbiggerarms-145x89.jpg 145w, http://blog.menscience.com/wp-content/uploads/2013/09/howtogetbiggerarms-150x92.jpg 150w, http://blog.menscience.com/wp-content/uploads/2013/09/howtogetbiggerarms-375x231.jpg 375w, http://blog.menscience.com/wp-content/uploads/2013/09/howtogetbiggerarms.jpg 568w" sizes="(max-width: 145px) 100vw, 145px">							
				</a>
		</div>-->
		

	    <header class="entry-header">
	     <h2 class="entry-title">
		  <a href="<?php echo str_replace('clnews', $item->getAlias(), $item->getUrl()) ?>" title="How to Get Bigger Arms"><?php echo $item->getTitle(); ?></a>
		 </h2>
	    </header>

    </article>					
	<?php endforeach; ?>	   
	</div>

	</div>


		
		
		

	</div>

		<aside id="sidebar" class="sidebar right">
		<style>
.rpwe-block ul{list-style:none!important;margin-left:0!important;padding-left:0!important;}.rpwe-block li{border-bottom:1px solid #eee;margin-bottom:0px;padding-bottom:0px;list-style-type: none;}.rpwe-block a{display:inline!important;text-decoration:none;}.rpwe-block h3{background:none!important;clear:none;margin-bottom:0!important;margin-top:0!important;font-weight:400;font-size:14px!important;line-height:1.5em;}.rpwe-thumb{border:1px solid #EEE!important;box-shadow:none!important;margin:2px 10px 2px 0;padding:3px!important;}.rpwe-summary{font-size:12px;}.rpwe-time{color:#bbb;font-size:11px;}.rpwe-comment{color:#bbb;font-size:11px;padding-left:5px;}.rpwe-alignleft{display:inline;float:left;}.rpwe-alignright{display:inline;float:right;}.rpwe-aligncenter{display:block;margin-left: auto;margin-right: auto;}.rpwe-clearfix:before,.rpwe-clearfix:after{content:"";display:table !important;}.rpwe-clearfix:after{clear:both;}.rpwe-clearfix{zoom:1;}
</style>
<?php //$items = $item->getLatestNewsItems(); 
$collection = Mage::getModel('clnews/news')->getCollection()
            ->addStoreFilter(Mage::app()->getStore()->getId());
        $collection->setPageSize($this->_latestItemsCount);
        $collection
            ->addEnableFilter(1)
			->setPageSize(20)
            ->addFieldToFilter('publicate_from_time', array('or' => array(
                0 => array('date' => true, 'to' => date('Y-m-d H:i:s')),
                1 => array('is' => new Zend_Db_Expr('null'))),
                ), 'left')
            ->addFieldToFilter('publicate_to_time', array('or' => array(
                0 => array('date' => true, 'from' => date('Y-m-d H:i:s')),
                1 => array('is' => new Zend_Db_Expr('null'))),
                ), 'left')
            ->setOrder('news_time ', 'desc');
			
?>

<?php if(count($collection)): ?>
<div id="rpwe_widget-2" class="widget rpwe_widget recent-posts-extended">
	<h4 class="widget-title"><span>Recent Posts</span></h4>

	<div class="rpwe-block ">
	
	<ul class="rpwe-ul">
	<?php foreach ($collection as $item): ?>
	
           <?php if ($item->getData('status') == 1):?>
	<li class="rpwe-li rpwe-clearfix">
	<a class="rpwe-img" href="<?php echo str_replace('clnews', $item->getAlias(), $item->getUrl()) ?>" rel="bookmark">
	
	<?php if ($item->getImageFullContentShow() && $item->getImageFullContent()): ?>
	<?php $imageSize = $this->getShortImageSize($item) ?>
	<img class="rpwe-alignleft rpwe-thumb rpwe-default-thumb" src="<?php echo Mage::helper('clnews')->resizeImage(str_replace('clnews/', '', $item->getImageFullContent()), $imageSize['width'], $imageSize['height'], 'clnews'); ?>" alt="" width="45" height="45"></a>
	<?php endif; ?>
	<h3 class="rpwe-title"><a href="<?php echo str_replace('clnews', $item->getAlias(), $item->getUrl()) ?>" title="" rel="bookmark"><?php echo $item->getTitle();?></a></h3>
	<time class="rpwe-time published" datetime="2017-03-02T14:42:44+00:00"><?php echo Mage::helper('clnews')->formatDate($item->getNewsTime()) ?></time>
	</li>
	<?php endif; ?>
    <?php endforeach; ?>
	</ul>
	       
	</div><!-- Generated by http://wordpress.org/plugins/recent-posts-widget-extended/ -->
	</div>
<?php endif ?>	
	</aside>









<!---------------aneel----------------->

    
    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
	<?php $item = $this->getNewsitem(); ?>
	<?php //echo $item->getComments_enabled(); ?>
    
    <div class="news-item-comment">
    <?php if($item->getCommentsEnabled()): ?>
        <?php $comments = $this->getComments(); ?>
        <div>
            <a name="commentBox" ></a>
            <h2><?php echo $this->getCommentTotalString($comments);?></h2>
        </div>
        <div id="clloader" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/clnews/ajax-loader.gif')?>"/></div>
        <div id="comment_block">
        <?php $k = 0;?>
        <?php foreach ($comments as $comment):  ?>
            <div id="comment_item_<?php echo $k;?>" class="comment-item">
                <h4 class="username"><?php echo $comment->getUser();?></h4>
               <p> <?php echo $this->__("posted on:")?> <?php echo Mage::helper('clnews')->formatDate($comment->getCreatedTime());?></p>
                <p><?php echo $comment->getComment();?></p>
            </div>
            <?php $k++;?>
        <?php endforeach; ?>
        </div>
		
		
        <?php if($this->getLastPageNum()>1): ?>
            <div class="pager">
                <p class="page">
                <span id="prev"><span class="prev" style="display:none;"><?php echo $this->__('Previous') ?></span></span>
                <?php foreach ($this->getPages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <span id="page_<?php echo $_page ?>" class="page current" onclick="AjaxSend(<?php echo $_page ?>, <?php echo $item->getId() ?>, true);"><?php echo $_page ?></span>
                    <?php else: ?>
                        <span id="page_<?php echo $_page ?>" class="page" onclick="AjaxSend(<?php echo $_page ?>, <?php echo $item->getId() ?>, true);"><?php echo $_page ?></span>
                    <?php endif ?>
                <?php endforeach; ?>
                    <span id="next"><span class="next"><?php echo $this->__('Next') ?></span></span>
                </p>
            </div>
        <?php endif;?>
    
        <?php if (!$this->getRequireLogin() || ($this->getRequireLogin()&&$this->helper('customer')->isLoggedIn())): ?>
            <form id="postComment" method="post" action="">
                <h4><?php echo Mage::helper('clnews')->__('Submit Comment') ?></h4>
				</br>
                <ul>
                    <li>
                        <?php if (!$this->helper('customer')->isLoggedIn()): ?>
                            <div class="input-box">
                                <label for="name"><?php echo Mage::helper('clnews')->__('Name') ?> <span class="required"></span></label>
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('clnews')->getUserName()) ?>" class="required-entry input-text" type="text" />
                            </div>
                            <div class="clear"></div>
        
                            <div class="input-box">
                                <label for="email"><?php echo Mage::helper('clnews')->__('Email') ?> <span class="required"></span></label>
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('clnews')->getUserEmail()) ?>" class="required-entry input-text validate-email" type="text" />
                                <small><?php echo $this->__('(will not be displayed)') ?></small>
                            </div>
                        <?php else: ?>
                            <input name="post_id" type="hidden" value="<?php echo $item->getPostId();?>" />
                            <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('clnews')->getUserEmail()) ?>"/><br/>
                            <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('clnews')->getUserName()) ?>"/><br/>
                        <?php endif ?>
                        <div class="clear"></div>
                        <div class="input-box">
                            <label for="comment"><?php echo Mage::helper('clnews')->__('Comment') ?> <span class="required"></span></label>
                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('clnews')->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:400px;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                        </div>
                    </li>
                    <?php if (Mage::getStoreConfig('clnews/captcha/enabled')): ?>
                        <!-- - -->
                    <?php endif ?>
                    </li>
                </ul>
                <div class="button-set">
                    <input name="news_id" type="hidden" value="<?php echo $item->getId() ?>" />
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button class="button" type="submit"><span><span><?php echo Mage::helper('clnews')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>
        
            <script type="text/javascript">
            var contactForm = new VarienForm('postComment', false);
            </script>
        <?php else: ?>
            <p><?php echo Mage::helper('clnews')->__('You must be logged in to post a comment.');?></p>
            <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('clnews')->__('click here');?></a> <?php echo Mage::helper('clnews')->__('to log in');?></p>
        <?php endif; ?>
    <?php endif; ?>
    </div>
    <a href="<?php echo $this->getBackUrl() ?>" class="back">&laquo; <?php echo $this->__('Back') ?></a>
	
	
	

<script type="text/javascript">
    function AjaxSend(page, id, showLoader)
    {
        var url = "<?php echo Mage::getBaseUrl()?>clnews/newsitem/ajax/id/" + id + "/page/" + page + "/";
        if (showLoader) {
            jQuery("#clloader").css("display","block");
        }
        jQuery.ajax({
            url: url,
            dataType: 'json',
            success: function(data) {
                var content = '';
                jQuery(".comment-item").remove();
                for(var i = 0; i < data['dat'].cnt; i++) {
                    content = '<div id="comment_item_'+ i +'" class="comment-item"><h4 class="username">'+ data['collection'][i].user +'</h4> <?php echo $this->__("posted on")?> ' + data['collection'][i].created_time + '<div>' + data['collection'][i].comment + '</div></div>';
                    jQuery('#comment_block').append(content);
                }
                jQuery(".prev").remove();
                if (typeof(data['dat'].back_url) != 'undefined') {
                    jQuery("#prev").append('<span class="prev" ' + data['dat'].back_url + ' ><?php echo $this->__('Previous') ?></span>');
                }
                jQuery(".next").remove();
                if (typeof(data['dat'].fovard_url) != 'undefined') {
                    jQuery("#next").append('<span class="next" ' + data['dat'].fovard_url + ' ><?php echo $this->__('Next') ?></span>');
                }
                jQuery("#clloader").css("display","none");
            }
        });
        jQuery(".page").removeClass("current");
        var cl = 'page_' + page;
        jQuery("#" + cl).addClass("current");
    }
</script>
</div>
</div>
</div>