<div class="std testimonials_container">
    <h1 class="testimonials_title"><?php echo Mage::helper('testimonialmanager')->__('Write Testimonials'); ?></h1>

 <div class="testimonials-thumb">
        
       
        <?php $read = Mage::getSingleton('core/resource')->getConnection('core_read'); 
        $results = $read->fetchAll("SELECT * FROM `testimonialmanager` WHERE `menufecturer_id`='3' and status='2'");
        foreach($results as $result){  ?>
         <div class="testimonial_<?php $i++; echo (is_int($i/2) ? "r " : "l ")?>">
                            <?php if ($result['testimonial_img']): ?>
                                <?php endif; ?>
                                    <div class="testimonial_text">
                                        <div class="description-box">
                                            <?php echo $result['testimonial_text']; ?>
                                        
                                            <?php if($result['testimonial_website'] != '') { ?> <span><?php echo '<br>'.$result['testimonial_website']; ?></span>
                                                        <?php } ?>
                                        </div>
                                         
                                        
                                        <div class="rating-box">
                                            <div class="rating" style="width:<?php echo ceil($result['rating_summary'] * 20) ?>%;"></div>
                                        </div>
                                        <div class="testimonial_image"><?php if($result['testimonial_img'] != '') { ?> <img alt="<?php echo $result['testimonial_name']; ?>" src="<?php echo Mage::getBaseUrl('media').'/'.$result['testimonial_img']; ?>" width="120" height="120" /> <?php }  ?>   <span><?php echo $result['testimonial_name']; ?></span>
                                          <?php if($result['testimonial_company'] != '') { ?> <span style="display: inline;"><?php echo '<br>'.$result['testimonial_company']; ?></span>
                                                <?php }  ?>  
                                        </div>
                                         
                                    </div>
                                    
                        </div>
                         
<?php } ?>
    
                            <div class="clearer"></div>
    </div>

    
    <div class="testimonials-form">
		<form id="testimonialForm" name="testimonialForm" action="<?php echo $this->_getSubmitUrl() ?>" method="post" enctype="multipart/form-data">
            <table cellspacing="0" class="form-list" width="500">
                <tbody>
                   <tr> <!-- for store name and brand name-->
                        <td class="label"><label for="testimonial_brand"><?php //echo Mage::helper('testimonialmanager')->__('Contact Name') ?> </label></td>
                        <td class="value"><input type="hidden" class="" value="3" name="menufecturer_id" id="testimonial_name"></td>
                    </tr>
                    <tr> 
                        <td class="label"><label for="testimonial_brand"><?php //echo Mage::helper('testimonialmanager')->__('Contact Name') ?> </label></td>
                        <td class="value"><input type="hidden" class="" value="3" name="stores" id="testimonial_name"></td>
                    </tr>
                    <!-- store name and brand name end-->
                    <tr>
                        <td class="label"><label for="testimonial_name"><?php echo Mage::helper('testimonialmanager')->__('Contact Name') ?> <span class="required"></span></label></td>
                        <td class="value"><input type="text" class=" input-text required-entry" value="" name="testimonial_name" id="testimonial_name"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_company"><?php echo Mage::helper('testimonialmanager')->__('Product Name') ?></label></td>
                        <td class="value"><input type="text" class=" input-text" value="" name="testimonial_company" id="testimonial_company"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_email"><?php echo Mage::helper('testimonialmanager')->__('Email') ?> <span class="required"></span></label></td>
                        <td class="value"><input type="email" class=" validate-email input-text required-entry" value="" name="testimonial_email" id="testimonial_email" required></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_website"><?php echo Mage::helper('testimonialmanager')->__('City And State') ?><span class="required"></span></label></td>
                        <!--<td class="value"><input type="text" class="validate-clean-url input-text" value="" name="testimonial_website" id="testimonial_website"></td>-->
                        <td class="value"><input type="text" class="input-text required-entry" value="" name="testimonial_website" id="testimonial_website"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="testimonial_img"><?php echo Mage::helper('testimonialmanager')->__('Image') ?></label></td>
                        <td class="value"><input type="file" class="input-file" name="testimonial_img" id="testimonial_img"></td>
                    </tr>
                    <tr>
                        <td class="label"><label for="detailed_rating" class="rating"><?php echo Mage::helper('testimonialmanager')->__('Rating') ?> <span class="required"></span></label></td>
                        <td class="value">
                            <span id="detailed_rating"><div id="rating_detail"><div class="product-review-box">
                            <table cellspacing="0" id="product-review-table" width="250">
                                <thead>
                                <tr>
                                        <th><span class="nobr"><b><?php echo '1 star'; ?></b> </span></th>
									<?php for ($i=2; $i<=5; $i++) { ?>
                                        <th><span class="nobr"><b><?php echo $i . ' stars'; ?></b> </span></th>
                                    <?php } ?>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr class="odd last">
										<?php for ($i=1; $i<=5; $i++) { ?>
                                            <td<?php if($i == 5): ?> class="last"<?php endif; ?>><input type="radio" name="rating_summary" id="rating_<?php echo $i;?>" value="<?php echo $i ?>" checked="checked" /></td>
                                        <?php } ?>
                                    </tr>
                                </tbody>
                            </table>
                            </div></div></span>
                        </td>
                    </tr>
                    
                    <tr>
                        <td class="label"><label for="testimonial_text"><?php echo Mage::helper('testimonialmanager')->__('Text') ?> <span class="required"></span></label></td>
                        <td class="value">
                            <textarea class=" required-entry textarea" cols="15" rows="2" style="width:100%;height:200px;" title="Text" name="testimonial_text" id="testimonial_text"></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
            
            <div class="buttons-set">
                <button class="button" title="Submit Review" type="submit"><span><span><?php echo Mage::helper('testimonialmanager')->__('Submit Testimonial') ?></span></span></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonialForm', true);
//]]>
</script>