<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Shipping_Tracking
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div style="background:#f7f7f7; padding:12px;">
	<form action="<?php echo $this->getUrl('*/*/*') ?>" id="tracking-number" >
		<div class="fieldset">
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			<ul class="form-list">
	            <li class="fields">
	                <div class="customer-name">
					    <div class="field name-firstname">
					        <label for="firstname" class="required"><em>*</em><?php echo $this->__('Enter Tracking number') ?></label>
					        <div class="input-box">
					            <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="number" class="input-text required-entry">
					        </div>
					    </div>
					    <div class="field name-lastname">
					        <label for="lastname" class="required"><em>*</em><?php echo $this->__('Postal Services') ?></label>
					        <div class="input-box">
					            <select id="carrier" name="carrier" title="<?php echo $this->__('Carrier') ?>" class="required-entry">
					        		<?php foreach( array('ups' => 'UPS', 'fedex' => 'FedEx', 'usps' => 'USPS') as $carrier => $title) { ?>
					        			<?php if (Mage::getStoreConfig('shippingtracking/'.$carrier.'_api/enabled')) { ?>
					        				<option value="<?php echo $carrier ?>" <?php if ($this->getCarrier() == $carrier) echo 'selected="selected"' ?>><?php echo $title ?></option>
					        			<?php } ?>
					        		<?php } ?>
					        	</select>
					        </div>
					    </div>
					</div>
	            </li>
	        </ul>
	    </div>
	    <div class="buttons-set">
	        <p class="back-link">
	        	<a href="<?php echo $this->getUrl('*/', array('order' => $this->getRequest()->getParam('order'))) ?>">
	        		<small>« </small>
	        		<?php echo $this->__('Back') ?>
	        	</a>
	        </p>
	        <button type="submit" title="<?php echo $this->__('Track') ?>" class="button">
	        	<span><span><?php echo $this->__('Track') ?></span></span>
	        </button>
	    </div>
	</form>
</div>



<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('tracking-number');
    //]]>
</script>