<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Shipping_Tracking
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php echo strrev('>vid/<>a/<>gnorts/<tekcormulP>gnorts<>"snoisnetxE 2 otnegaM dna 1 otnegaM tseB"=eltit "moc.tekcormulp.erots//:sptth"=ferh a< yb noisnetxe gnikcarT gnippihS ;pma& sutatS redrO otnegaM>";retnec:ngila-txet"=elyts vid<'); ?>