
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
//$_productCollection = $this->getQuickattriute(); 
//echo $storeId = Mage::app()->getStore()->getStoreId();
//echo $websiteId = Mage::app()->getStore()->getWebsiteId();

$websiteIds = Mage::app()->getStore()->getWebsiteId();
$storeId = Mage::app()->getStore()->getStoreId();

$_productCollection = Mage::getModel('catalog/product')->getCollection()
            ->addAttributeToSelect('*')->addAttributeToFilter('quickorder', 1);
$_productCollection->addStoreFilter($storeId);
$_productCollection->addWebsiteFilter($websiteIds);



//$_productCollection = Mage::getModel('catalog/product')->getCollection()
//                    ->addAttributeToSelect('*')->setStoreId($storeId);

$quickorderguest = Mage::getStoreConfig('quickorder/quickorder/quickorderguest');
$quickordercartguest = Mage::getStoreConfig('quickorder/quickorder/quickordercartguest');
?>
<?php if(!count($_productCollection)): ?>  
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<form id="quick-order" action="<?php echo $this->getUrl('quickorder/index'); ?>" method="post" class="data-table">
<div class="category-products">
	<?php echo $this->getSortbarHtml() ?>
    <?php $_iterator = 0; ?>
    <?php if($this->helper('customer')->isLoggedIn()){ ?>
		<div style="margin-bottom: 5px;width: 100%;text-align: right;"><button type="submit" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
    <?php } ?>
    <?php if(!$this->helper('customer')->isLoggedIn() && ($quickordercartguest == '1')){ ?>
		<div style="margin-bottom: 5px;width: 100%;text-align: right;"><button type="submit" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
    <?php } ?>
    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="data-table" id="products-list">
	<tbody>
		<tr class="productListing-rowheading">
			<th align="center" id="listCell0-0" scope="col" class="productListing-heading"><?php echo $this->__('Product Image') ?></th>
			<th id="listCell0-1" scope="col" class="productListing-heading"><?php echo $this->__('Item Name') ?></a></th>
			<?php if($this->helper('customer')->isLoggedIn()): ?>
			<th align="right" id="listCell0-2" scope="col" class="productListing-heading"><?php echo $this->__('Price') ?></th>
			<th align="right" id="listCell0-2" scope="col" class="productListing-heading"><?php echo $this->__('Qty') ?></th>
			<th align="right" id="listCell0-2" scope="col" class="productListing-heading"><?php echo $this->__('Action') ?></th>
			<?php endif; ?>
			<?php if(!$this->helper('customer')->isLoggedIn() && ($quickorderguest == '1')):?>
			<th align="right" id="listCell0-2" scope="col" class="productListing-heading"><?php echo $this->__('Price') ?></th>
			<?php elseif (!$this->helper('customer')->isLoggedIn() && ($quickorder1 == '0')): ?>
			<div class="pri"><p>"Login to view product price"</p></div>
			<?php endif; ?>
			<?php if(!$this->helper('customer')->isLoggedIn() && ($quickordercartguest == '1')): ?>
			<th align="right" id="listCell0-2" scope="col" class="productListing-heading"><?php echo $this->__('Qty') ?></th>
			<th align="right" id="listCell0-2" scope="col" class="productListing-heading"><?php echo $this->__('Action') ?></th>
			<?php elseif (!$this->helper('customer')->isLoggedIn() && ($quickordercartguest == '0')): ?>
			<div class="pri"><p><?php echo $this->__('Login to Add to cart') ?></p></div>
			<?php endif; ?>
		</tr>
		<?php foreach ($_productCollection as $_product): ?>
			<tr class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
				<td align="center" class="productListing-data productListing-img">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" width="50"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				</td>
				<td class="productListing-data">
					<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
					<h3 class="product-name">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_product->getName(); ?></a>
					</h3>
					<div class="listingDescription">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('view more') ?></a>
					</div>
				</td>
				<?php if($this->helper('customer')->isLoggedIn()): ?>
				<td align="right" class="productListing-data">
					 <?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?>
				</td>
				<?php elseif (!$this->helper('customer')->isLoggedIn() &&($quickorderguest == '1')): ?>
				<td align="right" class="productListing-data">
					 <?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?>
				</td>
				<?php endif; ?>
				<?php if($this->helper('customer')->isLoggedIn()): ?>
				<td align="right" class="productListing-data">
					<input type="text" name="all[<?php echo $_product->getId(); ?>][qty]" id="qty" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
				</td>
				<td align="right" class="productListing-data productListing-addto">
					 <input type="checkbox" class="checkbox" name="all[<?php echo $_product->getId(); ?>][checkbox]" value="1">
					 <input type="hidden" name="all[<?php echo $_product->getId(); ?>][product_id]" value="<?php echo $_product->getId(); ?>" />
				</td>
				<?php elseif (!$this->helper('customer')->isLoggedIn() && ($quickordercartguest == '1')): ?>
				<td align="right" class="productListing-data">
					<input type="text" name="all[<?php echo $_product->getId(); ?>][qty]" id="qty" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
				</td>
				<td align="right" class="productListing-data productListing-addto">
					 <input type="checkbox" class="checkbox" name="all[<?php echo $_product->getId(); ?>][checkbox]" value="1">
					 <input type="hidden" name="all[<?php echo $_product->getId(); ?>][product_id]" value="<?php echo $_product->getId(); ?>" />
				</td>
				<?php endif ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
    </table>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    <?php if($this->helper('customer')->isLoggedIn()){ ?>
		<div style="margin-bottom: 5px;width: 100%;text-align: right;"><button type="submit" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" ><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
    <?php } ?>
</div>
</form>
<?php endif; ?>
    
